name: release jeecg-boot-vue
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jeecgboot-vue3
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: print files
        run: ls -al ./
      - name: tar files
        run: tar -czf archive.tar.gz dist
      - name: Get time
        id: get_time
        run: |
          echo $(date +'%Y-%m-%d-%H-%M-%S')
          echo "{TIME}={$(date +'%Y-%m-%d-%H-%M-%S')}" >> "$GITHUB_OUTPUT"
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.TOKEN }}
          working_directory: ./jeecgboot-vue3
          tag_name: stage-2026-05-20
          files: archive.tar.gz
