name: release jeecg-boot-vue
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jeecgboot-vue3
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: print files
        run: ls -al ./
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          working_directory: dist
          tag_name: stage-2026-05-20
          files: /*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
