name: test release

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jeecgboot-vue3
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: |
          mkdir dist
          echo ${{ github.sha }} > dist/Release.txt
      - name: Test
        run: |
          pwd
          cat dist/Release.txt
          tar -czf archive.tar.gz dist
      - name: Get time
        id: get_time
        run: echo ::set-output name=TIME::$(date +'%Y-%m-%dT%H:%M:%S')
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.get_time.outputs.TIME }}
          working_directory: ./jeecgboot-vue3
          token: ${{ secrets.TOKEN }}
          files: archive.tar.gz
